# -*- coding: utf-8 -*-
"""Warehouse campaign assets, part B: ad groups 4-6."""
AG={}
AG["Warehouse Fire & Smoke"]={
"intent":"Early fire and smoke detection inside warehouses and cold storage",
"url":"https://www.viact.ai/warehouse-safety",
"headlines":[
 "500+ Projects Worldwide","200+ Safety Modules","{KeyWord:Early Smoke Detection}",
 "AI Fire & Smoke Detection","Early Smoke Detection AI","Detect Smoke On Camera",
 "Fire Risk Alerts In Seconds","Warehouse Fire Detection AI","Cold Storage Fire Detection",
 "Monitor High-Rack Storage","Works With Existing CCTV","No Extra Sensors Needed",
 "For 3PL & Fulfilment Sites","Multi-Site Fire Monitoring","Cover Racking And Aisles",
 "Alert Before Flames Spread","24/7 Automated Watch","Protect Stock And People",
 "Book A Warehouse Demo","Talk To A Safety Engineer"],
"descriptions":[
 "AI Spots Smoke And Flame On Your Existing Cameras And Alerts Instantly.",
 "Cover High-Rack Storage And Aisles Where Point Detectors Are Slow To React.",
 "Retrofit To Your Existing Warehouse CCTV. No New Sensors Required.",
 "Book A Technical Demo With Our Team. 500+ Projects Worldwide.",
 "Built For 3PL, Fulfilment And Cold Storage Operators Running Multiple Sites.",
 "Monitor Every Site From One Dashboard And Escalate Alerts Automatically.",
 "Send Verified Camera Footage With Every Alert So Teams Can Act Fast.",
 "Watch Charging Bays, Racking And Packaging Zones Around The Clock.",
 "Reduce The Time Between Ignition And The First Human Response.",
 "200+ Safety Modules Covering Fire, Forklifts, PPE And Restricted Zones."],
"keywords":[
 ("early smoke detection warehouse","Phrase","Transactional","Warehouse-qualified","Named in the brief as a starter term"),
 ("ai fire detection system","Phrase","Transactional","Direct category match","Appeared in viAct's own data at HK$13.40 a click"),
 ("video smoke detection system","Phrase","Transactional","Technology-specific","Video qualifier means camera-based, which is what viAct sells"),
 ("warehouse fire detection system","Phrase","Transactional","Warehouse-qualified","System language signals procurement"),
 ("ai fire detection cold storage","Phrase","Transactional","Segment-qualified","Cold storage is a named target segment"),
 ("[video smoke detection]","Exact","Transactional","Core term protected","Exact stops drift to smoke alarms and extinguishers"),
 ("camera based fire detection","Phrase","Transactional","Technology-specific","Explicitly camera-based, matching the product"),
 ("early fire detection warehouse ai","Phrase","Transactional","Fully qualified","Combines urgency, setting and technology"),
]}
AG["Restricted Zone Access"]={
"intent":"Stopping unauthorised entry into dangerous or restricted warehouse zones",
"url":"https://www.viact.ai/warehouse-safety",
"headlines":[
 "500+ Projects Worldwide","200+ Safety Modules","{KeyWord:Restricted Zone Monitoring}",
 "AI Restricted Zone Alerts","Stop Unauthorised Entry","Danger Zone Detection AI",
 "Warehouse Perimeter Alerts","Detect Entry In Risk Zones","Protect Machinery Zones",
 "Monitor Charging Bays","Works With Existing CCTV","No Barriers Or Turnstiles",
 "For 3PL & Fulfilment Sites","Multi-Site Zone Control","Alert On Zone Breaches",
 "Log Every Zone Entry","Control High-Risk Areas","Evidence For Every Breach",
 "Book A Warehouse Demo","Talk To A Safety Engineer"],
"descriptions":[
 "AI Alerts The Moment Someone Enters A Restricted Or High-Risk Warehouse Zone.",
 "Draw A Zone On Camera And Get Alerted Without Fences, Gates Or Turnstiles.",
 "Retrofit To Your Existing Warehouse CCTV. No New Hardware Required.",
 "Book A Technical Demo With Our Team. 500+ Projects Worldwide.",
 "Protect Charging Bays, Baler Areas And Automation Zones From Foot Traffic.",
 "Built For 3PL, Fulfilment And Cold Storage Operators Running Multiple Sites.",
 "Every Breach Is Logged With Footage So HSE Teams Have Evidence.",
 "Manage Zone Rules Across Every Distribution Centre From One Platform.",
 "See Which Zones And Shifts Generate The Highest Breach Counts.",
 "200+ Safety Modules Covering Zones, Forklifts, PPE And Loading Docks."],
"keywords":[
 ("restricted area monitoring system","Phrase","Transactional","Direct category match","System language signals procurement"),
 ("danger zone detection warehouse","Phrase","Transactional","Warehouse-qualified","Names viAct's module and the setting"),
 ("warehouse perimeter monitoring ai","Phrase","Transactional","Technology-qualified","Named in the brief as a starter term"),
 ("unauthorised access detection warehouse","Phrase","Transactional","Fully qualified","Describes the exact outcome wanted"),
 ("ai zone intrusion detection","Phrase","Transactional","Technology-specific","AI qualifier reaches vision buyers"),
 ("[restricted zone monitoring]","Exact","Transactional","Core term protected","Exact stops drift to access-control hardware"),
 ("warehouse exclusion zone safety","Phrase","Commercial","Warehouse-qualified","Exclusion zone is the HSE term for the same need"),
]}
AG["Warehouse Safety Platform"]={
"intent":"Evaluating a multi-module warehouse safety platform at enterprise level",
"url":"https://www.viact.ai/warehouse-safety",
"headlines":[
 "500+ Projects Worldwide","200+ Safety Modules","{KeyWord:Warehouse Safety Software}",
 "AI Warehouse Safety Suite","One Platform, Every Hazard","Warehouse Safety Platform",
 "AI Video Analytics For DCs","Multi-Site Safety Control","Enterprise Warehouse Safety",
 "Forklift, PPE & Dock In One","Works With Existing CCTV","Roll Out Across Every Site",
 "Built For 3PL Operators","Safety Data In One Place","Replace Manual Safety Checks",
 "For Cold Storage & Fulfilment","Deploy Across Continents","Beyond PPE And Near Misses",
 "Book A Warehouse Demo","Talk To A Safety Engineer"],
"descriptions":[
 "One AI Layer Over Your Existing Cameras Covering Forklifts, PPE, Docks And Zones.",
 "Built For 3PL, Fulfilment And Cold Storage Operators Running Multiple Sites.",
 "Retrofit To Your Existing Warehouse CCTV. No New Cameras Or Rewiring.",
 "Book A Technical Demo With Our Team. 500+ Projects Worldwide.",
 "Give Group HSE One Dashboard Across Every Distribution Centre.",
 "Compare Safety Performance By Site, Shift And Hazard Type.",
 "Replace Manual Walkarounds With Continuous Automated Monitoring.",
 "Every Incident Recorded With Footage, Ready For Audit Or Insurer Review.",
 "Start With One Site, Then Roll The Same Platform Out Across The Network.",
 "200+ Safety Modules Covering Forklifts, PPE, Docks, Fire And Restricted Zones."],
"keywords":[
 ("warehouse safety software","Phrase","Transactional","Core category term","Software buyer, not a training or PPE buyer"),
 ("warehouse safety monitoring system","Phrase","Transactional","System-level buyer","System language signals procurement"),
 ("ai video analytics warehouse","Phrase","Transactional","Technology-qualified","Named in the brief as a starter term"),
 ("warehouse cctv analytics","Phrase","Commercial","Technology-qualified","Analytics layer over existing CCTV, matching the offer"),
 ("3pl safety software","Phrase","Transactional","Segment-qualified","Names the highest-value buyer segment"),
 ("distribution centre safety software","Phrase","Transactional","Segment-qualified","DC language reaches network operators"),
 ("[warehouse safety software]","Exact","Transactional","Core term protected","Exact holds the head term against drift"),
 ("[warehouse safety monitoring system]","Exact","Transactional","Core term protected","Exact holds the head term against drift"),
 ("ai safety monitoring for logistics","Phrase","Transactional","Sector-qualified","Logistics qualifier reaches 3PL and fulfilment"),
 ("cold storage safety monitoring","Phrase","Transactional","Segment-qualified","Cold storage is a named target segment"),
 ("multi site warehouse safety system","Phrase","Transactional","Enterprise signal","Multi-site is the clearest enterprise qualifier available"),
]}
