# -*- coding: utf-8 -*-
"""Warehouse campaign assets, part A: ad groups 1-3."""
AG={}
AG["Forklift Pedestrian Safety"]={
"intent":"Buying a system that stops forklift-pedestrian collisions",
"url":"https://www.viact.ai/warehouse-safety",
"headlines":[
 "500+ Projects Worldwide","200+ Safety Modules","{KeyWord:Forklift Safety System}",
 "Forklift Pedestrian Detection","Stop Forklift Near Misses","AI Forklift Collision Alerts",
 "Alerts Before Impact","Detect Workers In Aisles","Forklift Proximity Alerts",
 "Warehouse Vehicle Safety AI","Protect Warehouse Pedestrians","AI Camera For Forklifts",
 "Works With Existing CCTV","Retrofit, No New Vehicles","For 3PL & Fulfilment Sites",
 "Multi-Site Forklift Safety","Blind Corner Detection","Reduce Forklift Incidents",
 "Book A Warehouse Demo","Talk To A Safety Engineer"],
"descriptions":[
 "AI Detects Workers Near Forklifts And Alerts Drivers Before A Collision Happens.",
 "Retrofit To Your Existing Warehouse CCTV. No Vehicle Hardware, No Rewiring.",
 "Built For 3PL, Fulfilment And Cold Storage Operators Running Multiple Sites.",
 "Book A Technical Demo With Our Team. 500+ Projects Worldwide.",
 "Monitor Aisles, Blind Corners And Loading Zones From One Central Dashboard.",
 "Flag Unsafe Proximity Between Forklifts And Pedestrians In Real Time.",
 "Deploy Across Every Distribution Centre From A Single Safety Platform.",
 "Give HSE Teams Evidence Of Every Near Miss, Automatically Logged.",
 "See Where Forklift Risk Concentrates By Aisle, Shift And Site.",
 "200+ Safety Modules Covering Forklifts, PPE, Docks And Restricted Zones."],
"keywords":[
 ("forklift pedestrian detection","Phrase","Transactional","Names the exact module","Searcher is specifying the detection type they want to buy"),
 ("forklift pedestrian detection system","Phrase","Transactional","Exact product category","'system' signals a purchase, not research"),
 ("forklift collision avoidance system","Phrase","Transactional","Direct category match","Buying language for the same outcome"),
 ("forklift anti collision system","Phrase","Transactional","Direct category match","Appeared in viAct's own data at HK$26.80 a click"),
 ("forklift proximity detection system","Phrase","Transactional","Direct category match","Already reached viAct's ads historically"),
 ("warehouse forklift collision prevention","Phrase","Transactional","Warehouse-qualified","Warehouse qualifier filters out construction and port traffic"),
 ("forklift pedestrian safety system","Phrase","Transactional","Direct category match","System-level buyer language"),
 ("pedestrian detection system for forklifts","Phrase","Transactional","Direct category match","Long-form buying query"),
 ("[forklift pedestrian detection]","Exact","Transactional","Highest-intent core term","Exact protects the core term from broad drift"),
 ("[forklift collision avoidance system]","Exact","Transactional","Highest-intent core term","Exact protects the core term from broad drift"),
 ("ai forklift safety","Phrase","Commercial","Technology-qualified","AI qualifier separates vision buyers from sensor buyers"),
 ("forklift safety camera system","Phrase","Commercial","Camera-based buyer","Camera language means they expect a vision solution"),
]}
AG["Warehouse PPE Detection"]={
"intent":"Automating PPE compliance checks inside a warehouse",
"url":"https://www.viact.ai/warehouse-safety",
"headlines":[
 "500+ Projects Worldwide","200+ Safety Modules","{KeyWord:Warehouse PPE Detection}",
 "AI PPE Detection Warehouse","Automate PPE Compliance","Detect Missing Hi-Vis Vests",
 "Hard Hat & Vest Detection","Real-Time PPE Alerts","PPE Compliance Evidence",
 "Warehouse PPE Monitoring","Works With Existing CCTV","No New Cameras Needed",
 "For 3PL & Fulfilment Sites","Multi-Site PPE Compliance","Audit-Ready PPE Records",
 "Cut Manual PPE Checks","Detect Safety Shoes & Vests","Track PPE By Shift & Zone",
 "Book A Warehouse Demo","Talk To A Safety Engineer"],
"descriptions":[
 "AI Checks Hi-Vis, Hard Hats And Footwear On Every Camera, Every Shift.",
 "Replace Manual Walkaround Checks With Continuous Automated Monitoring.",
 "Retrofit To Your Existing Warehouse CCTV. No New Cameras Required.",
 "Book A Technical Demo With Our Team. 500+ Projects Worldwide.",
 "Give Auditors A Complete PPE Compliance Record Without Manual Logging.",
 "See PPE Compliance By Site, Zone And Shift From One Dashboard.",
 "Built For 3PL, Fulfilment And Cold Storage Operators Running Multiple Sites.",
 "Alert Supervisors The Moment Someone Enters A Zone Without Required PPE.",
 "Roll Out Across Every Distribution Centre From A Single Platform.",
 "200+ Safety Modules Covering PPE, Forklifts, Docks And Restricted Zones."],
"keywords":[
 ("warehouse ppe compliance","Phrase","Commercial","Warehouse-qualified PPE","Warehouse qualifier keeps construction traffic out"),
 ("ai ppe detection warehouse","Phrase","Transactional","Exact module match","Names technology and setting together"),
 ("ppe detection software","Phrase","Transactional","Software buyer","'software' filters out PPE suppliers"),
 ("ppe compliance monitoring system","Phrase","Transactional","System-level buyer","System language signals procurement"),
 ("automated ppe detection","Phrase","Transactional","Automation intent","Wants to replace a manual process"),
 ("hi vis vest detection","Phrase","Transactional","Specific detection type","Very specific, named in the brief"),
 ("[ai ppe detection]","Exact","Transactional","Core term protected","Exact stops drift to PPE retail"),
 ("[ppe detection system]","Exact","Transactional","Core term protected","Exact stops drift to PPE retail"),
 ("ppe monitoring software warehouse","Phrase","Transactional","Fully qualified","Every word signals a warehouse software buyer"),
 ("ppe compliance software for logistics","Phrase","Transactional","Sector-qualified","Logistics qualifier reaches 3PL buyers"),
]}
AG["Loading Bay Safety"]={
"intent":"Preventing incidents at loading docks and during vehicle reversing",
"url":"https://www.viact.ai/warehouse-safety",
"headlines":[
 "500+ Projects Worldwide","200+ Safety Modules","{KeyWord:Loading Dock Safety}",
 "AI Loading Bay Monitoring","Loading Dock Safety System","Truck Reversing Alerts",
 "Prevent Dock Incidents","Detect Unsafe Dock Access","Monitor Every Loading Bay",
 "Dock Plate Safety Alerts","Yard And Dock Monitoring","Works With Existing CCTV",
 "For 3PL & Fulfilment Sites","Multi-Site Dock Safety","Reduce Reversing Incidents",
 "Alert On Unsafe Yard Moves","Evidence For Every Incident","Protect Dock Workers",
 "Book A Warehouse Demo","Talk To A Safety Engineer"],
"descriptions":[
 "AI Watches Every Loading Bay And Flags Unsafe Vehicle And Worker Movement.",
 "Detect Reversing Risk, Unsafe Dock Access And Missing Dock Plates In Real Time.",
 "Retrofit To Your Existing Yard And Dock Cameras. No New Hardware.",
 "Book A Technical Demo With Our Team. 500+ Projects Worldwide.",
 "Built For 3PL, Fulfilment And Cold Storage Operators Running Multiple Sites.",
 "Give HSE Teams Recorded Evidence Of Every Dock Near Miss.",
 "Monitor Yard And Dock Activity Across Every Site From One Dashboard.",
 "Alert Supervisors Before A Reversing Vehicle Reaches A Pedestrian.",
 "See Which Bays And Shifts Generate The Highest Incident Counts.",
 "200+ Safety Modules Covering Docks, Forklifts, PPE And Restricted Zones."],
"keywords":[
 ("loading dock safety system","Phrase","Transactional","Direct category match","System language signals procurement"),
 ("loading bay monitoring system","Phrase","Transactional","Direct category match","Monitoring system is the product category"),
 ("loading dock safety ai","Phrase","Transactional","Technology-qualified","Named in the brief as a starter term"),
 ("truck reversing alert system","Phrase","Transactional","Specific hazard","Names the exact hazard and a system to fix it"),
 ("warehouse yard safety monitoring","Phrase","Commercial","Warehouse-qualified","Yard safety is a dock-adjacent buying theme"),
 ("dock safety monitoring software","Phrase","Transactional","Software buyer","Software qualifier filters out dock equipment sellers"),
 ("[loading dock safety system]","Exact","Transactional","Core term protected","Exact stops drift to dock levellers and equipment"),
 ("vehicle reversing detection warehouse","Phrase","Transactional","Fully qualified","Combines hazard, technology and setting"),
]}
