# -*- coding: utf-8 -*-
"""Brief v4 layer: structure, markets, competitive analysis, evidence."""
STRUCTURE=[
 ("Campaign 1","WH_Search_UK | Search | GBP 300/week",
  "Northampton, Milton Keynes, Leicester, Rugby DIRFT, London Gateway/Thurrock, Magna Park. 25-50 km radius each.",
  "Brief ranks UK #1. viAct has real UK history: 132 clicks at HK$25.10, CTR 7.32%."),
 ("Campaign 2","WH_Search_Canada | Search | CAD 400/week",
  "GTA - Mississauga, Milton, Brampton, Vaughan. Greater Vancouver - Delta, Surrey. Calgary.",
  "Brief ranks #2 on the argument that Voxel and Protex are US-focused and weak here."),
 ("Campaign 3","WH_Search_Australia | Search | AUD 400/week",
  "Sydney - Eastern Creek, Erskine Park, Kemps Creek, Prestons. Melbourne - Truganina, Somerton, Dandenong South. Brisbane - Larapinta.",
  "Brief ranks #3 on WHS and industrial-manslaughter liability driving safety spend."),
 ("Campaign 4","WH_Search_Ireland | Search | EUR 200/week",
  "Dublin - Blanchardstown, Ballycoolin, Citywest. Cork. Limerick.",
  "Brief ranks #4. See the competitive sheet - this is Protex AI's home market."),
 ("Campaign 5","WH_Search_USA_Narrow | Search | Month 2 only",
  "Inland Empire - Ontario, Rialto, Fontana CA. Dallas-Fort Worth TX. Lehigh Valley - Allentown PA.",
  "Brief holds this to Month 2. viAct's own US clicks cost HK$32.60, the most expensive of any market tested."),
 ("Campaign 6","WH_Pmax_Global_Warehouse | Performance Max | USD 500/week",
  "All four pilot markets","RECOMMEND DEFERRING - see the recommendations sheet."),
 ("Campaign type","Search only. Search partners OFF. Display expansion OFF.",
  "All four pilot campaigns","Display expansion on Search is a known low-quality click source."),
 ("Location targeting","Presence only - 'People in or regularly in your targeted locations'.",
  "All campaigns","Interest-based targeting is what lets overseas traffic in."),
 ("Language","English only.","All four pilot markets",
  "All four are English-speaking. This is the main practical advantage of v4 over v2, which needed Dutch, Arabic and Malay."),
 ("Excluded locations","Exclude India, Pakistan, Bangladesh, Nigeria, Philippines at campaign level.",
  "All campaigns","RECOMMENDATION. Presence-only should make this redundant; it costs nothing as a second layer."),
 ("Audience strategy","Observation only, never targeting. In-market Enterprise Software; Physical Security & Access Control; Business & Industrial Products; Material Handling Equipment. Custom segment from competitor URLs.",
  "All campaigns","Observation reads which audiences convert without restricting reach. Do NOT seed on broad 'all site visitors'."),
 ("Bidding weeks 1-3","Manual CPC with per-ad-group bid caps.","All campaigns",
  "The brief's own 30-day plan specifies manual CPC in week 2. No conversion history exists in Canada or Australia at all."),
 ("Bidding week 4+","Move an ad group to Maximise Conversions only after consistent conversions. Target CPA only past roughly 30 a month.",
  "All campaigns","Published guidance puts the practical automated-bidding minimum near 30 conversions a month."),
 ("Bid caps UK / Ireland","Forklift HKD 45 · PPE HKD 25 · Loading Bay HKD 35 · Fire HKD 30 · Zone HKD 30 · Platform HKD 40",
  "WH_Search_UK, WH_Search_Ireland","DERIVED FROM viAct'S OWN DATA: UK clicks averaged HK$25.10 and Ireland HK$26.80 on comparable terms."),
 ("Bid caps USA","Add roughly 30% to the UK caps if the Month 2 campaign launches.","WH_Search_USA_Narrow",
  "DERIVED FROM viAct'S OWN DATA: US clicks averaged HK$32.60 against HK$25.10 in the UK, on the same campaign."),
 ("Bid caps Canada / Australia","Start at the UK caps and review at day 7.","WH_Search_Canada, WH_Search_Australia",
  "FLAG: viAct has 113 lifetime impressions in Canada and 33 in Australia, and zero clicks in either. There is no cost data for these markets. The UK figure is a placeholder, not a forecast."),
 ("Ad groups","Six per campaign, one per module. Rename 'Warehouse Video Analytics' to 'Warehouse Safety Platform'.",
  "All campaigns","'Broad AI CCTV catch-all' is how a campaign drifts - HK_Pmax_4S is currently paying for 'food ai' for exactly that reason."),
 ("Match types","Phrase for coverage, Exact on each ad group's head term. No broad match at launch.",
  "All campaigns","Broad match with no history and no negative list spends a pilot budget on the wrong queries."),
 ("Conversion action","One primary: demo request on /warehouse-safety. Count ONE per click. All else secondary.",
  "All campaigns","A single primary action makes cost per demo readable against the brief's HKD 1,000 gate."),
 ("Conversion setup","Enhanced conversions on. Import qualified-lead status from CRM from week 3.",
  "All campaigns","Without sales feedback, bidding optimises toward whoever fills forms most cheaply."),
 ("Form protection","reCAPTCHA v3 plus required business email and company size.","Landing page",
  "The brief's landing page section still does not mention form protection."),
 ("Budget total","Approximately USD 1,600 per week across five campaigns.","All",
  "FLAG: the account bills in HKD. GBP, CAD, AUD, EUR and USD figures must be converted before entry. No exchange rate invented here."),
]
COMPETITIVE=[
 ("Protex AI","14 of the 19 sample ads","Headline: 'Reduce Incidents by up to 80% - Safety AI & Camera Analysis'. Also '80% Reduction in Site Risk', 'AI for Workplace Safety', 'Warehouse CCTV Safety Software - 24/7 Unsafe Event Capture', '24/7 PPE & Hi-Vis Detection'.",
  "Leads with a hard 80% number in almost every asset, plus 'privacy-preserving' as the second pillar and 'Enterprise EHS Teams' as the audience call-out. Sitelinks: 2-Min Demo Video, Product, Complete PPE Usage Detection, AI-Powered PPE Detection, Company, Contact, Build Custom Safety Rules.",
  "Dominant paid-search advertiser in this category. Runs a local ad showing a Dublin 2 address, 42 Westland Row - so Ireland is their home market, not open ground."),
 ("Voxel","1 of the 19 sample ads","Headline: 'Warehouse Safety AI Software - Supply chain Safety Software'. Description names forklift near-misses and PPE violations, 'using existing camera', 'across sites'.",
  "Positions on multi-site supply chain scope. Sitelinks: Warehousing Distribution, Prevent Incident Before Happen, Detects Risks in Real Time, About, Knowledge.",
  "Brief cites USD 64M funding and a US focus."),
 ("Intenseye","1 of the 19 sample ads","Headline: 'Intenseye - Intenseye AI Workplace Safety'. Description: 'Real-time video analysis to identify the root causes of workplace injuries'.",
  "Positions on root-cause analysis rather than detection alone.","Brief cites USD 94M funding and a US focus."),
]
POSITIONING=[
 ("'Works with your existing CCTV'","TABLE STAKES, not a differentiator",
  "Protex says 'Plugs into Existing CCTV'. Voxel says 'using existing camera'. Every competitor already says this.",
  "Keep it - it answers a real objection - but never lead with it. It will not win a click against Protex."),
 ("Percentage outcome claims","viAct CANNOT MATCH and should not try",
  "Protex leads with 'up to 80%' in nearly every asset and '10k hour reduction in audit admin' in display.",
  "viAct has no substantiated percentage, and inventing one breaks the account's own claim rules. Compete on a different axis entirely."),
 ("Privacy / worker anonymisation","GAP - viAct is silent",
  "Protex makes 'privacy-preserving' and 'privacy-first AI vision' a second pillar in nearly every ad.",
  "In UK, Ireland and Australia, worker-monitoring privacy is a genuine buying objection. If viAct anonymises or blurs, say so. If it does not, this is a product gap, not a copy gap. NEEDS PRODUCT CONFIRMATION before any claim is written."),
 ("Breadth of hazard coverage","viAct's strongest available wedge",
  "Protex ads focus on PPE and near-misses. Voxel names forklift and PPE. None advertises the full hazard range.",
  "'200+ Safety Modules' is an approved claim and covers more ground than any competitor advertises. Lead with breadth."),
 ("Deployment scale and geography","viAct's second wedge",
  "Competitors advertise regionally - Protex UK/Ireland/US, Voxel and Intenseye US.",
  "'500+ Projects Worldwide' is approved and speaks to a multinational 3PL that runs sites across continents."),
 ("Single-platform consolidation","Third wedge",
  "No competitor ad in the sample offers forklift, PPE, dock, fire and restricted zone as one purchase.",
  "The Suite story in the brief is the right instinct. It is the one claim viAct can make that the sample competitors do not."),
 ("Ireland market entry","HIGHEST DIFFICULTY of the four pilots",
  "Protex AI is headquartered at 42 Westland Row, Dublin 2 and runs local ads there.",
  "The brief ranks Ireland Tier 1 partly because VentureWave, the Series A lead, is Dublin-based. That is an investor reason, not a market reason. Expect the highest cost per click and the strongest incumbent. Consider running Ireland at a reduced budget until UK data proves the proposition."),
]
EVIDENCE=[
 ("LIMITATION","Google Keyword Planner remains unavailable. The developer token has explorer access only and generateKeywordIdeas returns DEVELOPER_TOKEN_NOT_APPROVED. No search volume, competition index or CPC forecast appears anywhere in this plan.","Google Ads API, retested 19 Aug 2026"),
 ("FIRST-PARTY DATA","United Kingdom: 1,804 impressions, 132 clicks, HK$3,316 spent, 0 conversions, HK$25.10 per click, 7.32% click-through.","viAct Forklift_Safety_System campaign"),
 ("FIRST-PARTY DATA","Ireland: 340 impressions, 26 clicks, HK$697 spent, 0 conversions, HK$26.80 per click, 7.65% click-through - the highest click-through of any market tested.","viAct Forklift_Safety_System campaign"),
 ("FIRST-PARTY DATA","United States: 2,392 impressions, 185 clicks, HK$6,033 spent, 6 conversions, HK$32.60 per click. The most expensive market viAct has tested.","viAct Forklift_Safety_System campaign"),
 ("FIRST-PARTY DATA","Canada: 113 lifetime impressions, ZERO clicks, across all campaigns. Australia: 33 lifetime impressions, ZERO clicks. Neither market has ever been meaningfully tested by viAct.","viAct account, all campaigns, Jan 2024 to Aug 2026"),
 ("WARNING","UK and Ireland together delivered 158 clicks and HK$4,013 of spend for ZERO conversions. Click-through was strong at 7.3-7.7%, so the ads earned attention. What was missing was a warehouse landing page - which is exactly what this brief proposes to build.","viAct account"),
 ("VERIFIED FROM YOUR SCREENSHOTS","Protex AI accounts for 14 of the 19 sample ads, Voxel 1, Intenseye 1. Protex runs a local search ad displaying 42 Westland Row, Dublin 2.","Sample ad copy document supplied 19 Aug 2026"),
 ("FIRST-PARTY DATA","2,075 warehouse-related search terms have already reached viAct's ads. 22 of the 28 recorded conversions came from OFF-TARGET queries such as 'fleet tracking monitoring' (8) and 'warehouse picking software in the usa' (7) - products viAct does not sell.","viAct account"),
 ("FIRST-PARTY DATA","'blaxtair pedestrian detection system' appears in viAct's own search history, confirming Blaxtair as a fourth competitor buyers compare against.","viAct account"),
 ("FROM THE BRIEF","Country ranking, clusters, segments, job titles, six module ad groups, starter keywords, day-1 negatives, weekly budgets and the 30-day gates are taken from brief v4 unaltered.","viAct Warehouse Campaign Brief v4"),
 ("FLAG","Your message says 9 priority countries. Brief v4 states '8 NEW countries' and its table lists eight: UK, Canada, Australia, Ireland, USA, Belgium, Germany, Italy. This plan covers the four Tier 1 pilots plus the USA narrow entry. Please confirm whether a ninth market was intended.","Brief v4 versus your message"),
 ("FLAG","Two lines proposed in the brief cannot be used as written. 'Alert Before Impact. Every Time.' is an absolute guarantee. '40+ warehouses live' is an unverified customer count. Both are categories removed from viAct's live account this week.","docs/BRAND_CLAIMS.md"),
 ("FLAG","The landing page /warehouse-safety still does not exist. Every asset here points at it. Nothing can launch until it is published.","Stated in the brief as a deliverable"),
 ("FLAG","The account bills in HKD. Brief budgets are in GBP, CAD, AUD, EUR and USD and must be converted before entry. No exchange rate has been invented.","viAct account currency"),
 ("ASSUMPTION","Search volume in the named clusters is assumed sufficient to sustain six ad groups per campaign. With Keyword Planner unavailable this cannot be checked in advance. If impressions are thin after 14 days, merge the five module ad groups into two.","Stated as an assumption"),
 ("ASSUMPTION","Canada and Australia are assumed to behave like the UK on cost per click. There is no viAct data for either. Review bids at day 7, not day 14.","Stated as an assumption"),
 ("RECOMMENDATION","Defer WH_Pmax_Global_Warehouse until the Search pilot has run 30 days and CRM feedback is flowing. viAct's existing HK_Pmax_4S has spent HK$30,324, sends 66% of budget to YouTube and Discover, has produced zero leads from YouTube in eleven months, and is already identified internally as the source of low-quality leads.","HK_Pmax_4S audit, this account"),
 ("RECOMMENDATION","Consider opening Ireland at half budget. Protex AI is headquartered there and advertises locally. The UK is the same language, six times the cluster count, and a market where viAct already has click data.","Based on the competitive sheet"),
]
